### ISSUE TITLE
APIs

### ISSUE THREAD

**Issue by conzty01** [ThomasTwiton/cs_seniorproject#53]
I have found [this tutorial](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api-mac?view=aspnetcore-2.1) for implementing API Controllers to our project.

**Comment by conzty01** [comment]
The specifics for what api functionality I need for the dashboard is as follows:

1) An api to load all of the `Profiles` who have applied for a given audition. This will use the `AuditionProfiles` table and I will provide the `AuditionId`.
2) An api to load all of the `Profiles` for all of the members of an ensemble. I will provide the 'EnsembleId'.
3) An api to load all of the information about a given `Audition`. I will provide the `AuditionId`.
4) An api to change all of the information about a given `Audition`. This is similar to our `Edit` pages. I will provide all the data and the `AuditionId`.
5) An api to close an `Audition` (set the closed date to now). I will provide the `AuditionId`.
6) An api to open an `Audition` (set the closed date to some time in the future). I will provide the `AuditionId`.
7) An api to add a `Profile` to an ensemble. I will provide the profile's name in the format `'First Last'` and the `EnsembleId`.
8) An api to remove a member from an ensemble. I will provide the `ProfileId` and `EnsembleId`
9) An api to accept an audition applicant as a new member of the ensemble. I will provide the `AuditionId`, `ProfileId`, and `EnsembleId`.
10) An api to delete an audition candidate. This will use the `AuditionProfiles` table and I will provide the `AuditionId` and `ProfileId`.

In the future, we will need similar apis for handling gigs, but we can focus on auditions for now.

**Comment by donnma01** [comment]
11. Add a Profile to AuditionProfiles

**Comment by donnma01** [comment]
9 seems pretty ambiguous. 7 seems to do the same thing.
